###################### Base Settings######################
test_during_training: True

### database ###
TID2013:
  datainfo: ./data/TID2013fullinfo.mat
  im_dir: ../../Dataset/tid2013/distorted_images/
TID2013blur:
  datainfo: ./data/TID2013info.mat
  im_dir: ../../Dataset/tid2013/distorted_images/
LIVE:
  datainfo: ./data/LIVEfullinfo.mat
  im_dir: ../../Dataset/LIVE/

patch_size: 32
stride: 32
flag: 1
is_norm: True

train_ratio: 0.6
val_ratio: 0.2
test_ratio: 0.2

### model ###
# CNNIQA:
#   kernel_size: 7
#   n_kernels: 50
#   n1_nodes: 800
#   n2_nodes: 800
