# Base Setting
test_during_training: True

# Database
TID2013:
  datainfo: ./data/TID2013fullinfo.mat
  im_dir: ../../Dataset/tid2013/distorted_images/
TID2013blur:
  datainfo: ./data/TID2013info.mat
  im_dir: ../../Dataset/tid2013/distorted_images/
LIVE:
  datainfo: ./data/LIVEfullinfo.mat
  im_dir: ../../Dataset/LIVE/

patch_size: 32
stride: 32
is_gray: True # is_gray whether to use Gray or RGB (input image)
is_norm: True # is_norm whether to use normalizaion or not (preprocessing)

# LIVE will error because size
# is_patch: True # is_patch whether to use patch or entire of an image

train_ratio: 0.6
val_ratio: 0.2
test_ratio: 0.2
